```{r}
library(animint2)
library(data.table)
library(reshape2)
```

```{r}
data.name <- "bacteria_fungi_conservative"
source_target.csv <- sprintf("necromass_%s_Pearson_source_target.csv", data.name)
weight.dt <- fread(source_target.csv)
data.list <- list()
for(data.type in c("power_transformed", "raw")){
  data.csv <- sprintf("%s_%s.csv", data.name, data.type)
  data.list[[data.type]] <- fread(data.csv)
}
norm01 <- function(x)(x-min(x))/(max(x)-min(x))
scatter.dt <- do.call(data.table, lapply(data.list[["power_transformed"]], norm01))
taxa.vec <- names(scatter.dt)
N.taxa <- ncol(scatter.dt)
weight.dt[source<target]
get_pair <- function(i, j){
  sprintf("%s, %s", taxa.vec[i], taxa.vec[j])
}
weight.dt[, pair := get_pair(target+1, source+1)]
##<20 is bacteria, >=20 is fungi.
(taxa.dt <- data.table(
  taxon=taxa.vec, taxon.i=seq(0, N.taxa-1)
)[, kingdom := {
  ifelse(taxon.i<19, "bacteria", "fungi")
}][, i.pi := {
  2*pi*taxon.i/.N
}][, `:=`(
  x=sin(i.pi), y=cos(i.pi)
)][])
source.xy <- taxa.dt[weight.dt, .(
  pair, source_x=x, source_y=y, target, weight), on=.(taxon.i=source)]
both.xy <- taxa.dt[source.xy, .(
  pair, target_x=x, target_y=y, source_x, source_y, target, weight), on=.(taxon.i=target)]
both.xy[, sign := ifelse(weight<0, "negative", "positive")]
pair.dt.list <- list()
text.dt.list <- list()
```


```{r}
group_dict <- list(
  #G1 = list(name = "Group 1", start = 1, end = 69),
  G2 = list(name = "AllSoilM1M3", start = 1, end = 23),
  G3 = list(name = "LowMelanM1", start = 24, end = 35),
  G4 = list(name = "HighMelanM1", start = 36, end = 46),
  G5 = list(name = "LowMelanM3", start = 47, end = 57),
  G6 = list(name = "HighMelanM3", start = 58, end = 69)
)
options(warn = -1)


```

```{r}

suppressWarnings({
  for (group_key in names(group_dict)) {
    g <- group_dict[[group_key]]
    
    for(var.x in seq(1, N.taxa-1)){
      for(var.y in seq(var.x+1, N.taxa)){
        
        pair <- get_pair(var.x, var.y)
        sub.scatter.dt <- scatter.dt[g$start:g$end, ]
        data.x=sub.scatter.dt[[var.x]]
        data.y=sub.scatter.dt[[var.y]]
        pair_group <- sprintf("%s, %s", pair, g$name)
          
        pair.dt.list[[pair_group]] <- data.table(
          pair,
          data.x,
          data.y,
          group = g$name
        )
        
        text.dt.list[[pair_group]] <- data.table(
          pair,
          p_cor = cor(data.x, data.y),
          sparsity = mean(c(data.x, data.y) == 0 ),
          taxon.x=taxa.vec[var.x],
          taxon.y=taxa.vec[var.y],
          group =g$name
        )
      } 
    }
  }


pair.dt <- rbindlist(pair.dt.list)
text.dt <- rbindlist(text.dt.list)
})
```

```{r}
abs_corr_threshold_values <- seq(0, 1, by = 0.1)
filtered_text.dt_list <- list()

for (threshold in abs_corr_threshold_values) {
  filtered_text.dt <- text.dt[abs(p_cor) >= threshold]
  filtered_text.dt[, abs_corr_threshold := threshold]
  filtered_text.dt_list[[as.character(threshold)]] <- filtered_text.dt
}

filtered_text.dt <- rbindlist(filtered_text.dt_list)
```


```{r}
group_names <- unique(filtered_text.dt$group)
group_comb <- combn(group_names, 2)
group.dt.list <- list()

for (i in 1:ncol(group_comb)) {
  sub_dt <- filtered_text.dt[group %in% group_comb[, i]]
  sub_dt[, p_cor_diff := rep(diff(p_cor), length.out = .N), by = pair]
  sub_dt[, sparsity_diff := rep(diff(sparsity), length.out = .N), by = pair]
  #sub_dt[, sparsity_diff := diff(sparsity), by = pair]
  sub_dt[, group_pair := paste(group_comb[, i], collapse = "-")]
  group.dt.list[[i]] <- sub_dt
}
group.dt <- rbindlist(group.dt.list)
```


```{r}
# Create the abs_corr_threshold values ranging from 0.0 to 1.0 with a step of 0.1
abs_corr_threshold_values <- seq(0, 1, by = 0.1)

# Initialize an empty list to store filtered data.tables
filtered_data_list <- list()

# Loop through each abs_corr_threshold value and filter rows accordingly
for (threshold in abs_corr_threshold_values) {
  filtered_data <- both.xy[abs(weight) >= threshold]
  filtered_data[, abs_corr_threshold := threshold]
  filtered_data_list[[as.character(threshold)]] <- filtered_data
}
# remove  both.xy from memory
# rm(list = c("both.xy"))
# Combine the filtered data.tables into a single data.table
filtered_both.xy <- rbindlist(filtered_data_list)

# Add a 'sign' column to the final data.table
filtered_both.xy[, sign := ifelse(weight < 0, "negative", "positive")]

# Now you have the modified 'both.xy' data.table with the 'abs_corr_threshold' column and filtered rows.
counts_dt <- filtered_both.xy[, .(count = .N), by = abs_corr_threshold]
counts_dt
```




```{r}
# Read the CSV file into R
data <- fread("2023-10-23_11:59_pearson_agg.csv")

# Convert the data into the desired format
my_errors_dt <- data.table(
  abs_corr_threshold = rep(data$reg_param_, each = 2),
  set = rep(c("subtrain", "validation"), times = nrow(data)),
  errors = c(data$subtrain_score_mean, data$validation_score_mean),
  variable = "errors"
)

my_model_info <- data.table(
  abs_corr_threshold = data$reg_param_,
  num.edges = data$edges_mean
)

# Using reshape2 to melt the data
my_model_info.tall <- melt(my_model_info, id.vars = "abs_corr_threshold")

```

```{r}
my_set.label.select <- data.table(
  abs_corr_threshold=range(my_errors_dt$abs_corr_threshold),
  set=c("validation", "subtrain"),
  hjust=c(1, 0))

set.labels <- my_errors_dt[my_set.label.select, on=list(abs_corr_threshold, set)]
set.labels
```




```{r}
viz <- animint(
  title=paste(data.name,"visualization"),
  
   selectModel=ggplot()+
    ggtitle("Select absolute correlation threshold") +
    geom_tallrect(aes(
      xmin=abs_corr_threshold-0.1,
      xmax=abs_corr_threshold+0.1),
      clickSelects="abs_corr_threshold",
      #showSelected = "abs_corr_threshold",
      alpha=0.5,
      data=my_model_info)+
    theme_bw()+
    theme(panel.margin=grid::unit(0, "lines"))+
    geom_line(aes(
      abs_corr_threshold, errors,
      group=set, color=set),
      data=my_errors_dt)+
    facet_grid(variable ~ ., scales="free")+
    geom_text(aes(
    abs_corr_threshold, errors, label=set,
    hjust=hjust,
    color=set),
    data=set.labels)+
    guides(color="none")+
    geom_line(aes(
      abs_corr_threshold, value),
      data=my_model_info.tall)+
    scale_color_manual(values = c("subtrain" = "orange", 
                                  "validation" = "purple")),
  
  network=ggplot()+
    ggtitle("Click edge to select pair")+
    theme(
      axis.line=element_blank(),
      axis.text=element_blank(), 
      axis.ticks=element_blank(),
      axis.title=element_blank(),
      panel.border=element_blank(),
      panel.background=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank())+
    coord_equal()+
    geom_segment(aes(
      target_x, target_y,
      xend=source_x, yend=source_y,
      color=sign),
      alpha=0.6,
      clickSelects="pair",
      showSelected = "abs_corr_threshold",
      data=filtered_both.xy) +
    geom_point(aes(
      x, y, fill=kingdom, tooltip=taxon),
      shape=21,
      size=4,
      data=taxa.dt)+
    scale_fill_manual(values=c(fungi="black", bacteria="white")),
  
  scatter=ggplot()+
    ggtitle("Normalized abundance for selected pair")+
    geom_point(aes(
      data.x, data.y, color = group),
      showSelected="pair",
      data=pair.dt)+
    geom_text(aes(
      0.5, -0.05, label=taxon.x),
      showSelected="pair",
      data=text.dt)+
    geom_text(aes(
      -0.05, 0.5, label=taxon.y),
      angle=90,
      showSelected="pair",
      data=text.dt),
  
  scatterSparsity=ggplot()+
    ggtitle("Select sparsity/p_cor level")+
    geom_point(aes(
      p_cor, sparsity, color = group),
      showSelected = c("pair","abs_corr_threshold"),
      color="black",
      size= 4,
      data=filtered_text.dt)+
    geom_point(aes(
      p_cor, sparsity, color = group),
      clickSelects="pair",
      showSelected = "abs_corr_threshold",
      data=filtered_text.dt),
  
  
  scatterSparsityDiff=ggplot()+
    ggtitle("Select sparsity/p_cor difference level")+
    geom_point(aes(
      p_cor_diff, sparsity_diff, color = group_pair),
       showSelected = c("pair","abs_corr_threshold"),
      color="black",
      size= 4,
      data=group.dt)+
    geom_point(aes(
      p_cor_diff, sparsity_diff, color = group_pair),
      clickSelects="pair",
      showSelected = "abs_corr_threshold",
      data=group.dt),

 
  #,out.dir = "~/Desktop/netviz"
  source = "https://github.com/tdhock/necromass/blob/feat/add_absolute_threshold/figure-one-network.Rmd"
  )

viz
```

```{r}
servr::httd("/private/var/folders/jf/1lv8wgr503396_w00202kgmw0000gp/T/RtmpeFijeQ/file4680377a0647")
```

```{r}
remotes::install_github("animint/animint2@84-move-gallery-from-blocks-to-gh-pages")
animint2pages(viz, "EngineerDanny-necromass-figure-one-network")
```


```{r}
N <- 3
set.seed(1)
demo_df <- data.frame(i=1:N, num=rnorm(N,2))
animint(
  defaults=ggplot()+
    ggtitle("Defaults, no color_off nor alpha_off")+
    geom_tile(aes(
      i, 0, fill=num),
      clickSelects="i",
      size=5,
      data=demo_df)+
    geom_point(aes(
      i, num),
      size=5,
      clickSelects="i",
      data=demo_df),
  off=ggplot()+
    ggtitle("User specified alpha_off and color_off")+
 
    geom_point(aes(
      i, -num),
      size=5,
      alpha=1,
      alpha_off=0.5,
      color="red",
      fill="grey",
      color_off="black",
      clickSelects="i",
      data=demo_df))

```

```{r}
servr::httd("/private/var/folders/jf/1lv8wgr503396_w00202kgmw0000gp/T/RtmpeFijeQ/file4680b604dcd")
```
